apiVersion: v1
kind: Service
metadata:
  name: {{ include "nanoserver.fullname" . }}
  labels:
    {{- include "nanoserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.gamePort }}
      targetPort: game
      protocol: TCP
      name: game
  selector:
    {{- include "nanoserver.selectorLabels" . | nindent 4 }}