{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nanoserver.serviceAccountName" . }}
  labels:
{{ include "nanoserver.labels" . | nindent 4 }}
{{- end -}}
